name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: ["staging"]

jobs:
  delpoy:
    name: Deploying Node.js
    runs-on: centos-latest

    steps:
      -uses: actions/checkout@v3
      -name: deploying application to EC2
       env:
        PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY  }}
        HOSTNAME: ${{ secrets.SERVER_HOST  }}
        USER_NAME: ${{ secrets.SERVER_USERNAME  }}

        run: |
          ssh ${USER_NAME}@${HOSTNAME} touch test.txt

