name: Deploy
on:
  push:
    branches: ["staging"]

jobs:
  build:
    name: Deploying Node.js
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USERNAME}}
          key: ${{secrets.SERVER_SSH_KEY}}
          port: 22
          script: |
            cd /projects/test-deploy/
            git pull origin staging
            git status
            npm i
            pm2 stop all
